# Generated by Django 5.1.15 on 2026-04-23 19:10

import apps.institution_verification.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionVerificationCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        default=apps.institution_verification.models.generate_verification_reference,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("human_review_pending", "Human Review Pending"),
                            (
                                "ai_rejected_high_confidence",
                                "AI Rejected High Confidence",
                            ),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("correction_requested", "Correction Requested"),
                        ],
                        default="draft",
                        max_length=40,
                    ),
                ),
                (
                    "latest_submission_source",
                    models.CharField(
                        choices=[
                            ("institution_portal", "Institution Portal"),
                            ("support_reupload", "Support Re-upload"),
                        ],
                        default="institution_portal",
                        max_length=32,
                    ),
                ),
                ("support_reupload_allowed", models.BooleanField(default=False)),
                ("current_submission_ai_bypassed", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_human_review_routed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_cases",
                        to="institutions.institution",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_institution_verification_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionAIScreeningResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("flagged_for_human_review", "Flagged For Human Review"),
                            ("rejected_high_confidence", "Rejected High Confidence"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verification_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_screening_results",
                        to="institution_verification.institutionverificationcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionVerificationDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("correction_requested", "Correction Requested"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institution_verification_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="institution_verification.institutionverificationcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionVerificationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("bar_registration", "Bar Registration"),
                            ("authorization", "Authorization"),
                            ("tax_document", "Tax Document"),
                            ("identity", "Identity"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("file_reference", models.CharField(max_length=500)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "upload_source",
                    models.CharField(
                        choices=[
                            ("institution_portal", "Institution Portal"),
                            ("support_reupload", "Support Re-upload"),
                        ],
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_institution_verification_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="institution_verification.institutionverificationcase",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
