# Generated by Django 5.1.15 on 2026-04-23 19:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "duration_months",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Month"),
                            (3, "3 Months"),
                            (6, "6 Months"),
                            (12, "12 Months"),
                        ]
                    ),
                ),
                (
                    "base_price_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["duration_months", "base_price_amount", "code"],
            },
        ),
        migrations.CreateModel(
            name="ChargeSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "discounted_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(max_length=3)),
                ("scheduled_for", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("charge_in_progress", "Charge In Progress"),
                            ("charge_succeeded", "Charge Succeeded"),
                            ("charge_failed", "Charge Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "seven_day_reminder_due_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "seven_day_reminder_marked_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "three_day_reminder_due_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "three_day_reminder_marked_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_schedules",
                        to="access_billing.accessplan",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChargeAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_name", models.CharField(blank=True, max_length=64)),
                (
                    "provider_attempt_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                ("attempted_at", models.DateTimeField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=128)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "captured_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "charge_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="access_billing.chargeschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-attempted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("99.99")),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("applies_to_all_plans", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_plans",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coupons",
                        to="access_billing.accessplan",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="chargeschedule",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charge_schedules",
                to="access_billing.coupon",
            ),
        ),
        migrations.CreateModel(
            name="InstitutionAccessState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("eligible_to_start", "Eligible To Start"),
                            ("access_active", "Access Active"),
                            ("access_expiring_soon", "Access Expiring Soon"),
                            ("awaiting_first_charge", "Awaiting First Charge"),
                            ("paid_active", "Paid Active"),
                            ("payment_due", "Payment Due"),
                            ("payment_failed", "Payment Failed"),
                            ("recovery_active", "Recovery Active"),
                            ("paused_or_restricted", "Paused Or Restricted"),
                        ],
                        default="not_started",
                        max_length=32,
                    ),
                ),
                (
                    "access_period_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("access_period_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scheduled_first_charge_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_charge_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_charge_failure_at", models.DateTimeField(blank=True, null=True)),
                ("recovery_started_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_state",
                        to="institutions.institution",
                    ),
                ),
                (
                    "selected_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institution_access_states",
                        to="access_billing.accessplan",
                    ),
                ),
            ],
            options={
                "ordering": ["institution__display_name"],
            },
        ),
        migrations.AddField(
            model_name="chargeschedule",
            name="access_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charge_schedules",
                to="access_billing.institutionaccessstate",
            ),
        ),
        migrations.CreateModel(
            name="PaymentMethodReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_name", models.CharField(max_length=64)),
                ("provider_customer_reference", models.CharField(max_length=255)),
                ("provider_payment_method_reference", models.CharField(max_length=255)),
                ("masked_display", models.CharField(max_length=64)),
                ("card_brand", models.CharField(blank=True, max_length=64)),
                (
                    "expiry_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "expiry_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_method_references",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="institutionaccessstate",
            name="active_payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_access_states",
                to="access_billing.paymentmethodreference",
            ),
        ),
    ]
